default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  # host: <%= ENV.fetch('DB_HOST', 'localhost') %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  # host: <%= ENV.fetch('DB_HOST', 'localhost') %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  # host: db
